import { TwitchPrivateMessage } from "@twurple/chat/lib/commands/TwitchPrivateMessage"
import { SelectFromList } from "./Utils"
import odstQuotesList from "../Data/Twitch/ODSTQuotes.json"

export function HandleOdstQuote(msg: TwitchPrivateMessage) {
    SelectFromList(odstQuotesList, msg)
}

export var quoteMap = [
    {
        Command: ["!quote"],
        Message: [
            '"nades = movement" - Wingman953 Sept 2021',
            '"oni pog" - Wingman953 Nov 2018',
            '"I can go deeper and I shall" - Wingman953 May 2021',
            '"Did you p3 your pants?"',
            '"have peace! have peace!!"',
            '"peace be with you!"',
            '"Every time I look in vc, two people are muted but never the same two people"',
            '"if he wanted to kill me i wouldnt let him"',
            '"I am not a quote machine"',
            '"finally someone else gets quoted thats not named jon"',
            "\"im 17, and she's 18... wait, does that mean she's a pedophile?\"",
            '"Y\'all remember when the nazis invaded germany?"',
            '"1:04:08 makes you look like a failure.  Like, "bro, you cant even get a 1:03?"  But a 1:05:58 is like, "Damn bro got the 1:05 what\'s up""',
            '"pain hurts"',
            '"is there any plastic in this game so we can kill the turtles"',
            '"dont be fat and I wont be mad at you" - Z',
            '"you cant cancel me, im rocket jon" - Rocket Jon',
            '"We\'ll look into it"',
            '"oh shit does this mean i dont have to put nohr in my title anymore when im hitting fat naires lfg" - guy who gets fat naires',
            '"i remember one time i got a baby polar bear into my house and then he grew up and murdered me"',
            '"I don\'t recommend stabbing yourself"',
            '"we totally were in the same call like 2 times, that should be enough to kiss tbh"',
            '"aseritogiffgsuifghosiufhs" - Sean, probably',
            '"Since everything is inconsistent is the universe rng" - Eggplant',
            '"I can\'t a beat a dog up in the door way how lame"',
            '"They opened a gym in the bathroom" - EggplantHydra the 53rd edition',
            '"too much bonking :(" - Wingman953 April 2020',
            '"I\'m doing pretty good." - iTheReptiliani',
            '"i\'m planning on going to marry mcthumbs" - egggranthydra53',
            '"Hello my fellow compatriots, I have noticed that one of our acquaintances named Nik, otherwise known under the online pseudonym "Wingman953", is similar in his composure to that of a brick." - McThumbs',
            '"They should put capybaras in this game, expect I would be mad to see them killed" - SkilledGames_',
            "\"I can't kill baby animals, that's my limit.\" - _GamesSkilled",
            '"Out of all the fire emblem characters, falco is my favorite"- Skilled',
            '"what if they ask you that on a job offerview" - ben',
            '"Far out" - Wingman953',
            '"Asking if you’re greening out is the nicest thing you can say to somebody" - qup',
        ],
    },
    {
        Command: ["!upliftmarine", "!crazedmarine"],
        AllMessages: true,
        Username: ["Wingman953", "CameraDancer", "thiccElite"],
        Message: [
            "Crazed Marine: \"No, no, no! You're not listening! It's a zoo, okay?\"",
            'Medic: "Well, technically it\'s a corporate-funded wildlife reserve."',
            'Crazed Marine: "Semantics! This whole place is one...big...cage!"',
            'Medic: "Listen, Marine. You\'re wounded, you need to try and relax."',
            'Crazed Marine: "Except we, we\'re the zebras. All fenced in...and ready for the slaughter!"',
            'Medic: "And the Covenant?"',
            'Crazed Marine: "They\'re the lions...RAAAR!"',
            'Medic: "Careful. I think you just strained a metaphor."',
            'Crazed Marine: "Oh, oh god! Is that...serious?"',
            'Medic: "Only if you keep it up."',
        ],
    },
    {
        Command: ["!datahiveengineers", "!dhengineers"],
        AllMessages: true,
        Username: ["Wingman953", "CameraDancer", "thiccElite"],
        Message: [
            'Buck: "I\'ve seen hundreds of these things today! Why is this one so important?"',
            'Dare: "This Engineer knows what the Covenant is after. If I could safely capture more of them I would. What they know can win the war!"',
            'Buck: "Oh."',
            'Dare: "You haven\'t...killed any of them, have you?"',
            'Buck: "No!"',
            'Buck: "Well, maybe one or...two."',
            'Dare (sarcastically): "Nice work."',
            'Buck: "How was I supposed to know?"',
        ],
    },
    {
        Command: ["!waterfront", "!waterfronthighway"],
        AllMessages: true,
        Message: [
            'Buck: "All clear, let\'s move!"',
            'Dare: "Where are we going exactly?"',
            'Buck: "Waterfront Highway! Fastest way out of the city."',
        ],
    },

    // VIP
    {
        Command: ["!cutscene"],
        Username: ["Wingman953", "CameraDancer"],
        AllMessages: true,
        Message: [
            "/me View of the Highway at dawn opens. Cut to Dare, The Rookie, Buck, and Vergil moving forward. Covenant CCS-class battlecruisers fly above. Dare points to one.",
            'Dare: "When did this happen?" | Buck: "They started showing up right before I went underground." | Dare: "And you waited until now to tell me that?"',
            "/me Buck takes off his helmet.",
            "Buck: \"Oh, I'm sorry, I was a little busy. Making sure perfume (points to Huragok) over here didn't take a round and blow us all up!\"",
            "/me The Huragok looks sad, and floats away.",
            'Dare: "Eddie Buck, always thinking with his gun. You haven\'t changed one bit!" | Buck: "Me? What about you? Oh, so full of big ONI secrets, couldn\'t even give a guy a yes or no answer!" | Dare: "That\'s not fair." | Buck: "Oh, you got that right!"',
            "/me The Rookie tries to motion to the two that the Hurok is gone, but to no avail.",
            'Dare: "I never thought I\'d see you again!" | Buck: "Yeah? Well...here I am!"',
            "/me A cruiser drops out of Slipspace attracting the attention of the squad.",
            'Dare: "We need to move. Now. Were you too busy to plan our exit?" | Buck: "I stole a Phantom. Yes. Thank you. I hid it in the shipyards down the highway. (Looks toward nearby Warthog) But I only have room for two, so...that thing\'s gonna have to sit on your lap."',
            "/me Buck points to where the Engineer was, then realizes that it is gone.",
            'Dare: "The Engineer, where did it go?"',
            "/me Everyone looks around in panic, and then to the Olifant next to them. The hatch opens, and the Huragok's tentacle appears. The Huragok sounds the horn twice. Dare runs up to the Olifant.",
            'Dare: "Keep me covered. And try to keep up." | Buck: "Take my advice, Rookie. If you ever fall for a woman, (puts on his helmet) make sure she\'s got balls."',
            "/me Buck nods and moves out, as the Rookie looks on.",
        ],
    },
]
