import { SelectFromList } from "./Utils.mjs"

export function HandleOdstQuote(originalMessage) {
    SelectFromList(odstQuotesList, originalMessage)
}

export var quoteMap = [
    {
        Command: ["!quote"],
        Message: [
            '"nades = movement" - Wingman953 Sept 2021',
            '"oni pog" - Wingman953 Nov 2018',
            '"I can go deeper and I shall" - Wingman953 May 2021',
            '"Did you p3 your pants?"',
            '"have peace! have peace!!"',
            '"peace be with you!"',
            '"Every time I look in vc, two people are muted but never the same two people"',
            '"if he wanted to kill me i wouldnt let him"',
            '"I am not a quote machine"',
            '"finally someone else gets quoted thats not named jon"',
            "\"im 17, and she's 18... wait, does that mean she's a pedophile?\"",
            '"Y\'all remember when the nazis invaded germany?"',
            '"1:04:08 makes you look like a failure.  Like, "bro, you cant even get a 1:03?"  But a 1:05:58 is like, "Damn bro got the 1:05 what\'s up""',
            '"pain hurts"',
            '"is there any plastic in this game so we can kill the turtles"',
            '"dont be fat and I wont be mad at you" - Z',
            '"you cant cancel me, im rocket jon" - Rocket Jon',
            '"We\'ll look into it"',
            '"oh shit does this mean i dont have to put nohr in my title anymore when im hitting fat naires lfg" - guy who gets fat naires',
            '"i remember one time i got a baby polar bear into my house and then he grew up and murdered me"',
            '"I don\'t recommend stabbing yourself"',
            '"we totally were in the same call like 2 times, that should be enough to kiss tbh"',
            '"aseritogiffgsuifghosiufhs" - Sean, probably',
            '"Since everything is inconsistent is the universe rng" - Eggplant',
            '"I can\'t a beat a dog up in the door way how lame"',
            '"They opened a gym in the bathroom" - EggplantHydra the 53rd edition',
            '"too much bonking :(" - Wingman953 April 2020',
            '"I\'m doing pretty good." - iTheReptiliani',
            '"i\'m planning on going to marry mcthumbs" - eggranthydra53',
            '"Hello my fellow compatriots, I have noticed that one of our acquaintances named Nik, otherwise known under the online pseudonym "Wingman953", is similar in his composure to that of a brick." - McThumbs',
            '"They should put capybaras in this game, expect I would be mad to see them killed" - SkilledGames_',
            "\"I can't kill baby animals, that's my limit.\" - _GamesSkilled",
            '"Out of all the fire emblem characters, falco is my favorite"- Skilled',
            '"what if they ask you that on a job offerview" - ben',
        ],
    },
    {
        Command: ["!upliftmarine"],
        AllMessages: true,
        Message: [
            "Crazed Marine: \"No, no, no! You're not listening! It's a zoo, okay?\"",
            'Medic: "Well, technically it\'s a corporate-funded wildlife reserve."',
            'Crazed Marine: "Semantics! This whole place is one...big...cage!"',
            'Medic: "Listen, Marine. You\'re wounded, you need to try and relax."',
            'Crazed Marine: "Except we, we\'re the zebras. All fenced in...and ready for the slaughter!"',
            'Medic: "And the Covenant?"',
            'Crazed Marine: "They\'re the lions...RAAAR!"',
            'Medic: "Careful. I think you just strained a metaphor."',
            'Crazed Marine: "Oh, oh god! Is that...serious?"',
            'Medic: "Only if you keep it up."',
        ],
    },
    {
        Command: ["!datahiveengineers", "!dhengineers"],
        AllMessages: true,
        Message: [
            'Buck: "I\'ve seen hundreds of these things today! Why is this one so important?"',
            'Dare: "This Engineer knows what the Covenant is after. If I could safely capture more of them I would. What they know can win the war!"',
            'Buck: "Oh."',
            'Dare: "You haven\'t...killed any of them, have you?"',
            'Buck: "No!"',
            'Buck: "Well, maybe one or...two."',
            'Dare (sarcastically): "Nice work."',
            'Buck: "How was I supposed to know?"',
        ],
    },
    {
        Command: ["!waterfront", "!waterfronthighway"],
        AllMessages: true,
        Message: [
            'Buck: "All clear, let\'s move!"',
            'Dare: "Where are we going exactly?"',
            'Buck: "Waterfront Highway! Fastest way out of the city."',
        ],
    },

    // VIP
    {
        Command: ["!cutscene"],
        Username: ["Wingman953", "CameraDancer"],
        AllMessages: true,
        Message: [
            "/me View of the Highway at dawn opens. Cut to Dare, The Rookie, Buck, and Vergil moving forward. Covenant CCS-class battlecruisers fly above. Dare points to one.",
            'Dare: "When did this happen?" | Buck: "They started showing up right before I went underground." | Dare: "And you waited until now to tell me that?"',
            "/me Buck takes off his helmet.",
            "Buck: \"Oh, I'm sorry, I was a little busy. Making sure perfume (points to Huragok) over here didn't take a round and blow us all up!\"",
            "/me The Huragok looks sad, and floats away.",
            'Dare: "Eddie Buck, always thinking with his gun. You haven\'t changed one bit!" | Buck: "Me? What about you? Oh, so full of big ONI secrets, couldn\'t even give a guy a yes or no answer!" | Dare: "That\'s not fair." | Buck: "Oh, you got that right!"',
            "/me The Rookie tries to motion to the two that the Hurok is gone, but to no avail.",
            'Dare: "I never thought I\'d see you again!" | Buck: "Yeah? Well...here I am!"',
            "/me A cruiser drops out of Slipspace attracting the attention of the squad.",
            'Dare: "We need to move. Now. Were you too busy to plan our exit?" | Buck: "I stole a Phantom. Yes. Thank you. I hid it in the shipyards down the highway. (Looks toward nearby Warthog) But I only have room for two, so...that thing\'s gonna have to sit on your lap."',
            "/me Buck points to where the Engineer was, then realizes that it is gone.",
            'Dare: "The Engineer, where did it go?"',
            "/me Everyone looks around in panic, and then to the Olifant next to them. The hatch opens, and the Huragok's tentacle appears. The Huragok sounds the horn twice. Dare runs up to the Olifant.",
            'Dare: "Keep me covered. And try to keep up." | Buck: "Take my advice, Rookie. If you ever fall for a woman, (puts on his helmet) make sure she\'s got balls."',
            "/me Buck nods and moves out, as the Rookie looks on.",
        ],
    },
    {
        Command: ["!cutscene"],
        AllMessages: true,
        Message: ["Sorry friend, no cutscene text for you."],
    },
]

const odstQuotesList = [
    // The Rookie
    '"..." - The Rookie',
    // Buck
    '"You know the music, time to dance." - Buck',
    '"Troopers! We are green, and very, very mean!" - Buck',
    '"Pucker up, Marines! I sure as hell ain\'t hosing out your pods!" - Buck',
    '"We are droppin\' into Hell, troopers! Time to grow a pair!" - Buck',
    '"Stabilize then pop your chutes! We\'re going in hard!" - Buck',
    '"Got a little Jackal problem!" - Buck',
    "\"Damn it, no! Veronica? Talk to me! Don't move! I'm coming, you hear?\" - Buck",
    '"Oh, you\'re a piece of work, Romeo." - Buck',
    '"Back inside! Let\'s find that Pelican!" - Buck',
    '"That did it! Shoot and scoot!" - Buck',
    '"Grab some ammo, Romeo. These boys won\'t need it." - Buck',
    '"Look out! Chieftain!" - Buck',
    '"Get. This. Thing. Off. Of. Me." - Buck',
    "\"He's got a punctured lung, can't breathe.\" - Buck",
    '"Trains ran underground up to the old city, we\'re gonna find one of the tunnels, walk on outta here." - Buck',
    "\"Wait here. We're gonna steal that ride. It's landing, now's our chance! Mickey! You're with me!\" - Buck",
    '"I lost something! (whispering) Now I know where to find her." - Buck',
    '"About this uh, asset. Feel free to fill me in whenever." - Buck',
    '"Whew! Lord, that thing stinks. Kinda reminds me of my-" - Buck',
    '"You did good Rookie, no doubt. But we\'re not out of this yet." - Buck',
    '"I stole a phantom, yes, thank you." - Buck',
    '"Take my advice, Rookie. You ever fall for a woman? Make sure she\'s got balls." - Buck',
    '"Take the wheel, Rookie. I\'ll ride shotgun." - Buck',
    '"It\'s too far to walk, Rookie. Get in the Warthog!" - Buck',
    '"Hey, uh, Captain? Pick a lane." - Buck',
    "\"Hey, hold up! It's a Gauss 'Hog. Let's change vehicles. Same deal, trooper: You drive, I shoot.\" - Buck",
    '"Assault Carrier! Ten o\'clock high! Look at the size of that thing!" - Buck',
    "\"Damn it, no! They're gonna burn this city and then glass the whole planet! Covenant bastards! It's just like Reach all over again!\" - Buck",
    "\"Just nice to know they really do listen. C'mon, let's get out of this city.\" - Buck",
    '"Mickey? I\'m sending you a very special co-pilot." - Buck',
    '"That look may work with the chicks, but not with me." - Buck',
    "\"I understand that in the military we aren't supposed to ask, but I think I don't have to with you.\" - Buck",
    "\"Last person who looked at me like that was the Captain. And I asked her to marry me, so... don't say I didn't warn you.\" - Buck",
    '"Look, I\'m not saying anything has to happen, but maybe later we just hold each other in our underwear or something, but now we have a job to do!" - Buck',
    '"Don\'t make me do something manly and impulsive." - Buck',
    '"Don\'t let that damn turret fire one more round!" - Buck',
    '"This is your 8 A.M. wake up call!" - Buck',
    '"Go through \'em like a one stoplight town." - Buck',
    '"Thank you for the shiny, pretty gun." - Buck',
    '"That was 800 yards with a bent scope!" - Buck',
    '"Heat in the pipe! That\'s what she said!" - Buck',
    '"Let me turret, you suck at it. Don\'t get mad, we all know it." - Buck',
    '"You know, they are more fun to fight than Elites." - Buck',
    '"Yep." - Buck',
    '"Gimmie a sec, aaaaannnnd OK." - Buck',
    '"Bam, said the lady." - Buck',
    '"Boom, headshot." - Buck',
    '"Whoops, dropped your brain!" - Buck',
    '"Nice catch! With your face." - Buck',
    '"Low on ammo." - Buck',
    '"Special delivery from kick your ass express!" - Buck',
    '"Putting the pineapple in there!" - Buck',
    '"That\'s right, right back to mommy" - Buck',
    '"The corp doesn\'t pay me enough for this kind of garbage collection," - Buck',
    '"You must be the stupidest apes in the whole damn \'verse!" - Buck',
    // Dare
    "\"That's what I miss most about you, Buck. The way your mouth's always move a little faster than your brain. - Dare\"",
    '"An overcharged Plasma Pistol shot will neutralize their shields, should also take down a Brute\'s armour." - Dare',
    '"Multiple hostiles closing in on my position. Listen carefully, if I don\'t make it..." - Dare',
    '"My beacon is active - need immediate assistance! Someone, please respond!" - Dare',
    "\"Buck, is that you? (Static) They've got me cornered! I'm low on ammo! If you can hear me, I'm on sub-level nine, near station t-\" - Dare",
    '"Some idiots blew the building at the top of the shaft. Woke the whole hive." - Dare',
    "\"Down there? That's the Superintendent. The AI that runs every system in the city. My mission — our mission, is to secure the Superintendent's data.\" - Dare",
    '"Not bad. You do know your stuff." - Dare',
    '"Wow. I\'m impressed!" - Dare',
    '"Something tells me you\'re not a rookie..." - Dare',
    '"Everything we need to know about the Covenant, what they\'re looking for under the city is right...in...here." - Dare',
    '"No time to explain but do not, I repeat, do not shoot anything pink!" - Dare',
    '"Don\'t worry. We have a key." - Dare',
    '"The Engineer still has shields, but they won\'t last long in a firefight. Take point, clear a path to Buck." - Dare',
    '"Covenant must have shut these doors. Give the Engineer a second to override the lock!" - Dare',
    '"I think the Engineer found a way to extend its shields, sent a current through the outer plating. I don\'t know how strong its shields are, so stay close." - Dare',
    '"I see a Scorpion tank up ahead. We\'ll need the extra firepower." - Dare',
    '"Trooper, I have a Tier One asset and a whole bunch of Covenant who want it dead. Whatever you\'re going to do...step on it!" - Dare',
    '"For replacements...you make one hell of a team." - Dare',
    '"ONI Officers know a hundred possible ways to kill a man. For you...one hundred and one ways." - Dare',
    '"Trust me, getting slapped in a helmet still hurts." - Dare',
    '"I recommend trying a lot harder." - Dare',
    '"What\'s the Covenant word for kiss my ass?" - Dare',
    '"Dodge this!" - Dare',
    '"FYI, this is the part where I kill you!" - Dare',
    // Mickey
    '"Hey! Where\'s the fight at?" - Mickey',
    '"Sure! As long as I get to drive the tank!" - Mickey',
    '"Hey, you wanna do this? Be my guest. But this, ain\'t... (presses button) a job you wanna rush." - Mickey',
    '"More Phantoms, look sharp!" - Mickey',
    "\"That's the last of 'em Dutch, come back to my position!\" - Mickey",
    "\"Alright, that's it. Transfer the detonation codes to my COM. If anyone's takin' this place out, it's gonna be me.\" - Mickey",
    '"I love blowing crap up Dutch, but this situation sucks." - Mickey',
    "\"This day ain't turnin' out so bad after all!\" - Mickey",
    '"Gunny, we\'ve moved one of those construction cranes — made a bridge to our location." - Mickey',
    '"Gunny, I can fly a Pelican, but a Phantom? It\'s been years since I even ran a simulation!" - Mickey',
    '"Gunny, more of those floating squids. Should we smoke \'em?" - Mickey',
    '"Ugh, cabin secure. Flight controls read green across the board...well, purple, but she\'s good to go...I think." - Mickey',
    '"Whoo-yeah! Line \'em up, boys!" - Mickey',
    '"I\'m gonna rip out your heart and show it to your dying eyes!" - Mickey',
    '"I am about to end your life!" - Mickey',
    '"Bullet, meet head. Head, meet bullet." - Mickey',
    "\"That's a stain that won't go away!\" - Mickey",
    '"You guys must be the Covenant B-team" - Mickey',
    '"That was a massacre! No, a slaughter! It was a massacre slaughter kill!" - Mickey',
    '"Your mama never loved ya and she dresses you funny." - Mickey',
    '"You will cease to live very soon!" - Mickey',
    '"Time for medicine." - Mickey',
    '"We\'ve got trouble, right here in River City." - Mickey',
    '"I saw my life flash before me. It sucked." - Mickey',
    '"That hurt! ...and my feelings, too." - Mickey',
    '"He was my friend." - Mickey',
    '"I... loved him!" - Mickey',
    '"I throw like a girl!" - Mickey',
    '"Backblast!" - Mickey',
    '"I know, I have beautiful eyes, right?" - Mickey',
    '"How did you ever get off your planet?" - Mickey',
    // Dutch
    "\"Relax Rookie. He don't mean nothin'. Besides, now's one of those times? Pays to be the strong, silent type.\" - Dutch",
    "\"Good hunting, boys... I'm keepin' my boots on the ground.\" - Dutch",
    '"We\'re down, Gunny. On a rooftop north-east of your location." - Dutch',
    "\"Uh, Lord? I didn't train to be a pilot. Tell me I don't have any more flying to do today.\" - Dutch",
    '"I\'m outta rockets! Kill that Wraith!" - Dutch',
    '"Bird\'s wasted. Lost the pilot on impact. Rest of us are okay." - Dutch',
    '"Well, look at that. I think we found us a squid house." - Dutch',
    '"Like the good book says, payback\'s a bitch!" - Dutch',
    "\"I'm paraphrasin', ya heathen!\" - Dutch",
    '"Get behind it! Shoot it in the ass!" - Dutch',
    '"Oorah Gunny, let it burn!" - Dutch',
    '"This is not going to plan, gorram it!" - Dutch',
    '"You ungainly, floundering, monstrous bag of horse crap!" - Dutch',
    '"You great big blot on the landscape!" - Dutch',
    '"You overgrown, pounderous, waste of mass, scumbag, runaway, jackass!" - Dutch',
    '"Roll over, Mike-Foxtrot, and get yourself foxtrotted!" - Dutch',
    '"Mike-Foxtrot. Is. Foxtrotted!" - Dutch',
    '"BAM!! Right in his sense of smug satisfaction!" - Dutch',
    '"GOT \'IM!!" - Dutch',
    '"I\'m sore, and tired, and ready for vengeance!" - Dutch',
    "\"I hope you bought return tickets, because otherwise you're goin' home in a cosmic ambulance!\" - Dutch",
    '"Dear Diary, today, I taught some aliens about the relative foolishness of messin\' with ODSTs!" - Dutch',
    "\"You think you can just barge in here and bend us over these- Well that ain't gonna happen! They told me to hurt ya, but they weren't real specific as to the how! OK?!\" - Dutch",
    "\"I'm gonna make sure that when we win, everyone's gonna know what a beating we gave you!\" - Dutch",
    '"I will rip off your arms and play bongos on your head." - Dutch',
    '"Hey scumbag! You seen Full Metal Jacket?" - Dutch',
    '"Enjoy that extra nose hole." - Dutch',
    '"Bim-bam in the brainpan." - Dutch',
    '"Go arou- oh wait, you\'re dead." - Dutch',
    '"(Oh) Sorry, didn\'t see you there." - Dutch',
    '"You malodorous leadfooted nimrod!" - Dutch',
    '"Laser up." - Dutch',
    '"Charged and ready." - Dutch',
    '"Don\'t nobody cross my stream..." - Dutch',
    '"If ya see red... heh... move." - Dutch',
    '"Time for a spanking!" - Dutch',
    '"Backblast!" - Dutch',
    '"Here\'s Vera!" - Dutch',
    '"Oh you finally decided to show your face, wait that is your face right?" - Dutch',
    '"I had them trying and ready for vengeance" - Dutch',
    '"Yeah, well, I\'m a frighteningly handsome young man, what of it?" - Dutch',
    "\"It ain't logical. I mean, hell, I'll kill a man in a fair fight... or if I think he's gonna start a fair fight, or if he bothers me, or if there's a woman... (sniffs) or if I'm gettin' paid - mostly only when I'm gettin' paid.\" - Dutch",
    '"What? They don\'t have awesome heroes back where you come from?" - Dutch',
    '"I know, you\'re trying to figure out what makes me so awesome. (chuckles) Good luck." - Dutch',
    '"Don\'t make me write you up to HR. You were at the seminar." - Dutch',
    '"You know, if there\'s something you want to tell me, uh, it should really wait until after this galaxy-devouring conflict." - Dutch',
    '"Hey, don\'t worry, everyone finds my chiseled looks hypnotic at first." - Dutch',
    '"Well... uh... like, you know, so you know, it\'s a major city, so... we have to assault with, uh, Scorpions. So they send us in, first squad, make sure, you know, the little Grunts waiting with, uh, you know, like, the plasma cannons that blow the tanks away, so... you know, we clear it out, roll the hogs in... basically blow the place to hell." - Dutch',
    // Romeo
    "\"Give it up, Gunny. Even if he ain't dead he's lost in that soup. Our comms can't cut through that.\" - Romeo",
    '"Thanks for choosing a tall building, I\'m really digging these stairs." - Romeo',
    '"That\'s the bridge?! You have gotta be kidding me!" - Romeo',
    "\"Sure... What's the hurry, right? I'll just sit here, bleeding through my foam...\" - Romeo",
    "\"That's right, you damn aliens. Doesn't feel so good does it?\" - Romeo",
    '"Ah! This is the best mission ever!" - Romeo',
    '"We went through hell for that?" - Romeo',
    '"Clint Eastwood ain\'t got a patch on me!" - Romeo',
    "\"Ay, Clint Eastwood's got nothin' on me!\" - Romeo",
    '"Scoreboard." - Romeo',
    '"I\'m gonna kill you! With light!" - Romeo',
    '"Go get a Scarab ya sissies!" - Romeo',
    '"How\'s my driving? Call 1-800-SUCK-IT!" - Romeo',
    '"I\'m the back door man!" - Romeo',
    // Superintendent
    '"PLEASE REMAIN CALM." - Superintendent',
    '"KEEP IT CLEAN! RESPECT PUBLIC PROPERTY!" - Superintendent',
    '"BRIDGE TOLL ACCEPTED. HAVE A PLEASANT TRIP" - Superintendent',
    '"CONSTRUCTION AHEAD. EXPECT DELAYS." - Superintendent',
    '"WARNING! HITCHHIKERS MAY BE ESCAPED CONVICTS!" - Superintendent',
    '"WELCOME. ACCESS GRANTED." - Superintendent',
    '"CRIME DOESN\'T PAY. GOOD CITIZENS DO THEIR PART." - Superintendent',
    '"CAUTION, TRAVELER! CAUTION!" - Superintendent',
    '"ATTENTION, TRAVELER! LOST ITEM CAN BE CLAIMED ON...LOWER LEVELS." - Superintendent',
    '"SPAY AND NEUTER YOUR PETS. ALL DOGS MUST BE KEPT ON LEASH!" - Superintendent',
    // Johnson
    '"Don\'t worry...(tapping a control panel)...I know what the aliens like." - Johnson',
    '"Bip, bap, bam!" - Johnson',
    '"Sounds easy huh? WRONG!" - Johnson',
    '"See these skulls? When they activate, they turn a casual Covenant make out session, into a full on test of your manly prowess." - Johnson',
    '"Catch, makes the enemy toss grenades like it\'s going out of style." - Johnson',
    '"Black Eye, only way you\'re getting health back is by punching an alien in the chin." - Johnson',
    '"Bad ass, unlocked." - Johnson',
    "\"Now, I know what your thinking: 'Sergent Major Johnson, these sound like overwhelming odds. I don't want to drop into hell without an air tight insurance policy!' Well, do I have an offer for you! Pre-order your copy of Halo 3: ODST at participating retailers now and you'll get all the confidence you'll need: ME! Ha ha, that's right. The toughest, cigar chompest marine there is, yours to play in Firefight.\" - Johnson",
    // Chips Dubbo
    '"Trooper! Over here! I saw your pod hit... You\'re one lucky S.O.B." - Chips Dubbo',
    // Marines
    "\"Trooper, we're pinned down! Flank through this building, hit 'em from behind!\" - Marine",
    '"Thanks for the assist, trooper! Get this Warthog movin\', our CO needs us to clear this sector." - Marine',
    '"Watch that Chopper! Hit it head on, and it\'ll tear us to pieces." - Marine',
    "\"Nice of you to drop in, trooper. Head to the next section of the park, to my second platoon's location! They're taking heavy casualties, need immediate assistance.\" - Colonel",
    '"Find a hole in the wall, trooper! Drive right through it!" - Marine',
    "Look, the elevator! INCOMING!!! - Marine",
    '"Wanna live? Then get your ass out of the street!" - Marine',
    '"Get in the tank, trooper, before the Wraith takes it out!" - Marine',
    '""Ah, good work trooper! Covenant\'s been rollin\' us back block by block. Every Marine in the city is headed for a rally point near the Naval Intelligence building, you oughta come with us." - Marine',
    "\"We got a squad of Marines pinned down, far corner in the next plaza. It's packed with Covenant, trooper, so once you come in, don't stop movin'.\" - Marine",
    "\"Trooper, head through the doors to Kizingo Boulevard, fastest way to the rally point! Placin' a beacon on the door, let's move trooper! - Marine",
    '"Gauss Turret\'s hot, ready to fire!" - Marine',
    '"Thank God! Does one of you know how to use explosives?" - NMPD Officer',
    '"Signal\'s good! Arm the other detonators and pull back to me!" - NMPD Officer',
    '"Come on Super, unlock the keypad." - NMPD Officer',
    '"Hurry up men, check those charges!" - NMPD Sergeant',
    '"I have orders to deny enemy access to all classified data housed in this facility. You don\'t like it, jump your butts back into orbit!" - NMPD Sergeant',
    "\"What are you doing down here, anyway? Don't want to tell me? That's all right...we all have secrets.\" - NMPD Officer",
    '"You going down to Level 9 too? Guess I could use some backup..." - NMPD Officer',
    '"Kinsler gave me real specific instructions: Make sure the Doc\'s dead, and make double sure no one knows about it." - NMPD Officer',
    // Grunts
    '"Nah. If traitor escape, it their fault, not ours." - Grunt',
    '"Alarm! Intruder, in tunnels!" - Grunt',
    '"Prophets flare!" - Grunt',
    '"He has begun his journey" - Grunt',
    '"This one\'s for your momma!" - Grunt',
    '"My spidey sense is tingling!" - Grunt',
    '"It\'s the adversary!" - Grunt',
    // Brute
    '"Place the charge, before I lose my grip!" - Brute',
    '"Let no humans escape, to say what they have seen!" - Brute',
    '"We do the Prophets\' bidding, show no fear!" - Brute',
    '"Courage, warriors! Take this hill or DIE UPON IT!!!" - Brute',
    '"(roars) Open this door, traitor! - Brute',
    '"It has fallen back into cover" - Brute',
    '"Who does he think he is, Thor?" - Brute',
]
